# for local development
version: '2.3'
services:
  frontend:
    build:
      context: .
      target: 'build-stage'
    ports:
      - '8080:8080'
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    command: /bin/sh -c "npm run serve"